### ISSUE TITLE
Piano di progetto - prima stesura

### ISSUE THREAD

**Issue by SamuelPeron** [SWEasabi/documentazione#41]
Compiere una prima stesura del piano di progetto.

All'interno di questa prima stesura per quanto ne sappiamo ora dev'essere presente:

- [ ] introduzione
- [ ] analisi dei rischi
- [ ] pianificazione
- [ ] preventivo

**Comment by alessandro-massarenti** [comment]
Quando la versione 1.0.0 sarà pronta questa issue potrà essere chiusa, vedi repository [Piano di progetto]( https://github.com/SWEasabi/piano-di-progetto)
