### ISSUE TITLE
Piano di qualifica - prima stesura

### ISSUE THREAD

**Issue by SamuelPeron** [SWEasabi/documentazione#42]
Compiere una prima stesura del piano di qualifica

All'interno di questa prima stesura per quanto ne sappiamo ora dev'essere presente:

- [ ] introduzione
- [ ] qualità di processo
- [ ] qualità di prodotto
- [ ] testing

**Comment by alessandro-massarenti** [comment]
Quando la versione 1.0.0 sarà pronta questa issue potrà essere chiusa, vedi repository [Piano di qualifica]( https://github.com/SWEasabi/piano-di-progetto)
