### ISSUE TITLE
Aggiungere al README i repo dei submodule

### ISSUE THREAD

**Issue by alessandro-massarenti** [SWEasabi/documentazione#62]
Aggiungere al README i link ai repository dei sottomoduli, così da avere i riferimenti ai documenti inseriti in questo repository

**Comment by romano001** [comment]
Come vorresti aggiungere questi link? Nello stesso modo di come sono stati fatti i link per i pdf e le release?

**Comment by alessandro-massarenti** [comment]
Si, ti direi di si, vedi di mantenere l'ordine 

Però farei una sezione tipo

Contenuti inclusi:
- Link1
- Link2
- Link3

**Comment by alessandro-massarenti** [comment]
Manca il piano di progetto nei contenuti inclusi.

Separerei anche in:
- Assegnazione appalti
- RTB
- PB
- CA

Con le varie cose incluse

**Comment by romano001** [comment]
Vorresti quindi fare una cosa così?

Assegnazione appalti
- link1

RTB
- link2

etc.
