### ISSUE TITLE
Stendere lettera di candidatura PB Committente

### ISSUE THREAD

**Issue by alessandro-massarenti** [SWEasabi/documentazione#67]
Stendere la lettera di candidatura PB per il committente.

Con documenti allegati e quantaltro

**Comment by alessandro-massarenti** [comment]
@pierobonluca01 che documenti mancano per la lettera? riesci a farmi una lista delle versioni rilasciate ed i documenti da allegare?

**Comment by alessandro-massarenti** [comment]
@pierobonluca01 riesci a dirmi?

**Comment by pierobonluca01** [comment]
Piano di Progetto v2.0.1
Piano di Qualifica v2.0.0
Specifica Architetturale v1.0.0
Glossario v1.0.1
Verbali (v2.0.0)
Manuale Utente v1.0.0
Norme di progetto v2.0.0
